skip_branch_with_pr: true
build: off
skip_commits:
  files:
    - "README.md"

environment: 
  matrix:
    - GO_VERSION: "122"
    - GO_VERSION: "123"
    - GO_VERSION: "121"

  GOPATH: c:\gopath

before_test:
  - set PATH=C:\go%GO_VERSION%\bin;%PATH%
  - set GOROOT=C:\go%GO_VERSION%
  - set GOTOOLCHAIN=local


test_script:
  - go version
  - go env
  - go test -v ./...