name: test 

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: juanbarearojo0/privatechef
      options: --user root
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: test task
        run: task test
